Apple/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth.views import login
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from mainsite.views import set_language

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^lan/(?P<language>en|jp|zh-hant)$', set_language),
    url(r'^invoice/', include('invoice.urls')),
    url(r'^accounts/login/$', login)
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mainsite.urls')),
)

invoice/urls.py
from django.conf.urls import url

from . import views

app_name = 'invoice'
urlpatterns = [
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^$', views.root, name='root'),
    url(r'^search/$', views.search, name='search'),
    url(r'^search/(?P<invoice_id>\d+)$', views.search_detail, name='search_detail'),
    url(r'^choose/$', views.choose_create_invoice, name='choose_create_invoice'),
    url(r'^create/$', views.create, name='create'),
    url(r'^status/delete/$', views.delete, name='delete'),
    url(r'^status/confirm/$', views.confirm, name='confirm'),
    url(r'^edit/(?P<invoice_id>\d+)$', views.edit, name='edit'),
    url(r'^drawing/$', views.drawing, name='drawing'),
    url(r'^print/$', views.print_invoice, name='print'),
    url(r'^print_check/$', views.print_check_invoice, name='print_check'),
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^stats/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})$', views.stats, name='stats'),
    url(r'^check/$', views.check, name='check'),
    # url used for returning json objects (ajax)
    url(r'^furniture/$', views.get_furniture, name='get_furniture'),
    url(r'^edit/(?P<invoice_id>\d+)/invoice_products$', views.get_invoice_products, name='get_invoice_products'),
    url(r'^edit/(?P<invoice_id>\d+)/invoice_custom_products$', views.get_invoice_custom_products, name='get_invoice_custom_products')
]

invoice/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import base64
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.contrib.auth.models import User


class InvoiceQuerySet(models.query.QuerySet):
    def update(self, *args, **kwargs):
        # here queryset update method overridden
        kwargs['last_update'] = timezone.now()
        return super(InvoiceQuerySet, self).update(**kwargs)


class InvoiceManager(models.Manager):
    def get_queryset(self):
        # this is to use your custom queryset methods
        return InvoiceQuerySet(self.model, using=self._db)

class Branch(models.Model):
    branch_id = models.AutoField(primary_key=True)
    address = models.CharField(max_length=100)
    def __unicode__(self):
        return u'id:{} {}'.format(self.branch_id, self.address)

class Sales(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, null=True)
    sales_name = models.CharField(max_length=30)
    sales_id = models.AutoField(primary_key=True)
    branch = models.ForeignKey(Branch, null=True)
    def __unicode__(self):
        return u'{} id:{}'.format(self.sales_name, self.sales_id)

class Invoice(models.Model):
    objects = InvoiceManager()
    first_name = models.CharField(max_length=10)
    #initial = model
    Completed = 'C'
    Uncompleted = 'U'
    Deleted = 'D'
    Waiting = 'W'

    statuses = ((Uncompleted, 'Uncompleted'), (Completed, 'Completed'), (Deleted, 'Deleted'), (Waiting, 'Waiting'))

    Visa = 'V'
    EPS = 'E'
    Cash = 'C'

    payment_types = ((Visa, 'Visa'), (EPS, 'EPS'), (Cash, u'現金'))

    # Primary Data of an Invoice
    invoice_id = models.AutoField(primary_key=True)
    address = models.CharField(max_length=100)
    contact_number = models.CharField(max_length=8)
    home_number = models.CharField(max_length=8, default='')
    total_amount = models.IntegerField(default=0)
    discount = models.IntegerField(default=0)
    deposit = models.IntegerField(default=0)
    remaining = models.IntegerField(default=0)
    additional_note = models.CharField(max_length=100, default='')
    is_custom_made = models.BooleanField(default=False)
    payment_type = models.CharField(max_length=1, choices=payment_types, default=Cash)
    # DateTimeFields
    first_created = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    status = models.CharField(max_length=1, choices=statuses, default=Uncompleted)
    # related_invoice = models.IntegerField(default=0)
    sales = models.ForeignKey(Sales)
    customer = models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    # boolean used to indicate whether the invoice is waiting for checking or not

    # drawing = models.ImageField(upload_to='drawing', default='')

    def save(self, *args, **kwargs):
        self.last_update = datetime.now()
        self.remaining = self.total_amount - self.deposit
        return super(Invoice, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'{} {}'.format(self.invoice_id, self.first_name)

class ProductAddon(models.Model):
    price = models.IntegerField(default=0)
    description = models.CharField(max_length=20)

class Product(models.Model):
    Red_Cherry = models.BooleanField(default=False)
    Wooden_Black = models.BooleanField(default=False)
    Wooden_White = models.BooleanField(default=False)
    Light_Walnut = models.BooleanField(default=False)
    Maple = models.BooleanField(default=False)
    Oak = models.BooleanField(default=False)
    Glossy_White = models.BooleanField(default=False)
    Black_White = models.BooleanField(default=False)
    Cherry_White = models.BooleanField(default=False)
    Walnut_White = models.BooleanField(default=False)
    Glossy_Champagne = models.BooleanField(default=False)
    Wooden_Champagne = models.BooleanField(default=False)
    
    Other = models.BooleanField(default=True)

    price_multiplies = models.FloatField(default=1.6)
    product_id = models.AutoField(primary_key=True)
    serial_number = models.CharField(max_length=20)
    description = models.CharField(max_length=20)
    raw_price = models.IntegerField(default=0)
    price = models.IntegerField(default=0)

    is_wardrobe = models.BooleanField(default=False)
    red_apple = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if self.raw_price > 0:
            price = int(self.raw_price * self.price_multiplies)
            remainder = price % 10
            if remainder > 4:
                price += 10 - remainder
            else:
                price -= remainder
            self.price = price

        return super(Product, self).save(*args, **kwargs)

    # color = models.

    def __unicode__(self):
        return u'{3} {0} {1} ${2}'.format(self.serial_number, self.description, self.price, self.product_id)

    class Meta:
        ordering = ('serial_number',)

class InvoiceProduct(models.Model):
    Red_Cherry = 'R'
    Wooden_Black = 'B'
    Wooden_White = 'W'
    Light_Walnut = 'L'
    Maple = 'M'
    Oak = "A"
    Glossy_White = 'G'
    Black_White = 'BW'
    Cherry_White = 'CW'
    Walnut_White = 'WW'
    Glossy_Champagne = 'GC'
    Wooden_Champagne = 'C'

    Other = 'O'

    colors = ((Red_Cherry, u'紅櫻桃'), (Wooden_Black, u'黑橡'), (Black_White, u'黑橡/白'), (Cherry_White, u'紅櫻桃/白'),
              (Wooden_White, u'白木紋'), (Light_Walnut, u'淺胡桃'), (Walnut_White, u'淺胡桃/白'), (Glossy_Champagne, u'香檳亮光'),
              (Wooden_Champagne, u'香檳木紋'), (Maple, u'楓木'), (Oak, u'橡木'), (Glossy_White, u'白亮光'), (Other, u'其他'))

    invoice = models.ForeignKey(Invoice,on_delete=models.CASCADE)
    product = models.ForeignKey(Product)
    quantity = models.IntegerField()
    side_note = models.CharField(max_length=50, default='')
    color = models.CharField(max_length=2, choices=colors, default=Other)

    def __unicode__(self):
        return u'id:{} {} {} {}'.format(self.id, self.invoice_id, self.product_id, self.quantity)


class InvoiceCustomProduct(models.Model):
    invoice = models.ForeignKey(Invoice,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    quantity = models.IntegerField(default=0)
    price = models.IntegerField(default=0)
    color = models.CharField(max_length=50, default='')
    side_note = models.CharField(max_length=50, default='')

class InvoiceProductAddon(models.Model):
    invoice_product = models.ForeignKey(InvoiceProduct, on_delete=models.CASCADE)
    product_addon = models.ForeignKey(ProductAddon)

invoice/templates/invoice/check.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
      <meta name="apple-mobile-web-app-capable" content="yes">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'invoice/common.css' %}" />
      <link rel="stylesheet" type="text/css" href="{% static 'invoice/check.css' %}" />
      <script type="text/javascript" src="{% static 'common/jquery-3.1.1.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'invoice/main.js' %}"></script>
      <script>
          $(document).ready(apple.check.onload);
      </script>
  </head>
  <body>
    <header><span id="header_text">蘋果傢俬</span><a id="home" href="/invoice">主頁</a></header>
    <div class="main-container">
        {% if created == False %}
            <p id="invoice_left">{{ invoices.count }}張訂單未被核對</p>
            <ul>
                <li class="clickable"></li>
            {% for invoice in invoices %}
                <a href="{% url 'invoice:search' %}?search={{ invoice.invoice_id }}" style="text-decoration: none; color: black;display: block;">
                    <li class="invoice_detail_container">
                        <div id="first_name_container"><span id="first_name">{{ invoice.first_name }}</span><span class="invoice_id">#{{ invoice.invoice_id }}</span></div>
                    </li>
                </a>
            {% endfor %}
            </ul>
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="method" value="create" />
                <a href="#" class="menu-button" onclick="$(this).closest('form').submit()">製作對單紙</a>
            </form>
        {% else %}
            <p id="waiting_invoice">{{ invoices.count }}張訂單等待被核對</p>
            <ul>
                <li class="clickable"></li>
                {% for invoice in invoices %}
                    <a href="{% url 'invoice:search' %}?search={{ invoice.invoice_id }}" style="text-decoration: none; color: black;display: block;">
                        <li class="invoice_detail_container">
                            <div id="first_name_container"><span id="first_name">{{ invoice.first_name }}</span><span class="invoice_id">#{{ invoice.invoice_id }}</span></div>
                        </li>
                    </a>
                {% endfor %}
            </ul>
            <a href="{% url "invoice:print_check" %}" class="menu-button" onclick="$(this).closest('form').submit()">列印對單紙</a>
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="method" value="confirm" />
                <a id="confirm" href="#" class="menu-button" onclick="$(this).closest('form').submit()">確認</a>
            </form>
        {% endif %}
    </div>
  </body>
</html>

invoice/templates/invoice/choose_create_invoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'invoice/common.css' %}" />
    <script type="text/javascript" src="{% static 'common/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'invoice/main.js' %}"></script>
</head>
<body>
    <header><span id="header_text">蘋果傢俬</span><a id="home" href="/invoice">主頁</a></header>
<div class="main-container">
    <a href="{% url 'invoice:create' %}" class="menu-button">現成</a>
    <a href="" class="menu-button">訂造</a>
</div>
</body>
</html>

invoice/templates/invoice/choose_furniture.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <title></title>
    {% load static %}
    <script type="text/javascript" src="{% static 'common/jquery-3.1.1.min.js' %}"></script>
    <!-- <script type="text/javascript">
        var Product = function(n, s, p) {
            this.name = n;
            this.serial_number = s;
            this.price = p;
        }
        var products = [];
        {% for product in products %}products.push(new Product('{{ product.name }}', '{{ product.serial_number }}', {{ product.price }}));{% endfor %}
    </script> -->
    <link rel="stylesheet" type="text/css" href="{% static 'invoice/common.css' %}" />
    <link rel="stylesheet" media="screen and (max-width: 480px)" href="{% static 'invoice/furniture_mobile.css' %}" />
    <link rel="stylesheet" media="screen and (min-width: 480px)" href="{% static 'invoice/furniture.css' %}" />
    <script type="text/javascript" src="{% static 'invoice/QuantityBox.js' %}"></script>
    <script type="text/javascript" src="{% static 'invoice/main.js' %}"></script>
    <script type="text/javascript">
      $(document).ready(function() {
        apple.furniture.onload();
      });
    </script>
</head>
<body>
    <header><span id="header_text">蘋果傢俬</span><a id="home" href="/invoice">主頁</a></header>
    <div class="main-container">
        {% if has_product %}
          <p style="padding: 10px; font-size: 30px;margin: 20px 0;">此訂單已下單</p>
        {% endif %}
        <nav id="invoice_detail_container">
            <div id="first_name_container"><span id="first_name">{{ invoice.first_name }}</span><span class="invoice_id">#{{ invoice.invoice_id }}</span></div>
            <div id="invoice_detail_inner_container">
                <p>地址: {{ invoice.address }}</p>
                <p>電話: {{ invoice.contact_number }}</p>
            </div>
            <div id="cart_products_container">

            </div>
            <div style="padding: 10px">
             <textarea name="additional_note" form="form" placeholder="備註..."></textarea>
                <div id="edit_price_container">
                    <p>總值: <input form="form" type="number" id="total_amount" class="price-tag" value="0" name="price"/>
                    <p style="margin-top: 10px;">訂金: <input form="form" type="number" class="price-tag" value="0" name="deposite"/>
                </div>
            </div>
        </nav>
        <div>
            <input type="text" placeholder="傢俬編號" id="search_string_text_box" /><input type="submit" value="搜尋" id="submit_search_button"/>
        </div>
        <form method="post" id="form">
            {% csrf_token %}
            <div id="product_container">
            </div>
            <input style="float: right; margin: 15px 0;" type="submit" value="開單" />
        </form>

    </div>
    <div id="backdrop">
        <div id="quantity_selection_box">
            <div id="quantity_selection_box_info_container">
                <p>名稱: <span id="name_box_tag"></span></p>
                <p>編號: <span id="serial_box_tag"></span></p>
                <p>價錢: <span id="price_box_tag"></span></p>
                <p>數量: <input id="quantity_box_input" type="number" value="1" min="0"/></p>
                <span style="display: block;float: left;margin: 0 10px 0 5px;">追加: </span><textarea id="side-note" cols="40" rows="5"></textarea>
            </div>
            <div id="quantity_selection_box_button_container">
                <a class="quantity_box_button" id="cancel-button" href="javascript: void(0);">取消</a>
                <a class="quantity_box_button confirm" id="confirm-button" href="javascript: void(0);">確定</a>
            </div>
        </div>
    </div>
</body>
</html>

invoice/templates/invoice/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'invoice/common.css' %}" />
</head>
<body>
    <header><span id="header_text">蘋果傢俬</span><a id="home" href="/invoice">主頁</a></header>
</body>
</html>

invoice/templates/invoice/index.html
<html>
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width">
      <meta name="apple-mobile-web-app-capable" content="yes">
      {% load static %}
      <link rel="stylesheet" href="{% static 'common/bootstrap/css/bootstrap.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'invoice/common.css' %}" />
      <script type="text/javascript" src="{% static 'common/jquery-3.1.1.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'invoice/main.js' %}"></script>
      <style>
      a:hover {
        text-decoration: none;
      }
      .stared_list_item {
          background: rgb(245,245,245);
          padding: 10px;
          font-size: 20px;
      }
      ul li.stared_list_item:first-child {
          background: #3c465a;
          text-align: center;
          color: white;
      }
      span#address {
          margin: 0 7px;
      }
      .stared_list_item a div#detail_container {
          display: flex;
      }
      #detail_container span.invoice_id {
          flex: 1 0 auto;
          text-align: right;
      }
    </style>
  </head>
  <body>
    <header><span id="header_text">蘋果傢俬</span><a id="home" href="/invoice">主頁</a></header>
    <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12 text-center">
            <p style="margin: 10px 0;font-size: 25px;">你好，{{ user.username }} [<a style="text-decoration: underline; color: blue;" href="{% url 'invoice:logout' %}">登出</a>]</p>
            <ul class="invoice_list" id="stared_invoices_list">
                <li class="stared_list_item">
                    <div>重要訂單<label id="star" class="stared"></label></div>
                </li>
            </ul>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 button-container">
            <a href="{% url 'invoice:create' %}" class="menu-button">開單</a>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 button-container">
            <a href="{% url 'invoice:search' %}" class="menu-button">跟單</a>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 button-container">
            <a href="{% url 'invoice:check' %}" class="menu-button">對單</a>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 button-container">
            <a href="{% url 'invoice:stats' %}" class="menu-button">總結</a>
          </div>
        </div>
    </div>
    <script>
        apple.root.onload();
    </script>
  </body>
</html>

invoice/templates/invoice/search.html
<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width">
      <meta name="apple-mobile-web-app-capable" content="yes">
      {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'invoice/common.css' %}" />
      <link rel="stylesheet" media="screen and (max-width: 480px)" href="{% static 'invoice/search_mobile.css' %}" />
      <link rel="stylesheet" media="screen and (min-width: 480px)" href="{% static 'invoice/search.css' %}" />
      <script type="text/javascript" src="{% static 'common/jquery-3.1.1.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'common/drawingboard.nocontrol.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'invoice/main.js' %}"></script>
      <script type="text/javascript">
          $(document).ready(apple.search.onready);
      </script>
  </head>
  <body>
    <header><span id="header_text">蘋果傢俬</span><a id="home" href="/invoice">主頁</a></header>
    <div class="main-container" id="search_container">
        {% if not invoice %}
            <form method="get" style="position: relative">
                {% csrf_token %}
                <select name="cat" style="font-size:15px;position: absolute;width: 60px;height: 100%;border-top-right-radius: 0; border-bottom-right-radius: 0;">
                    <option value="invoice_id">訂單</option>
                    <option value="number">電話</option>
                    <option value="address">地址</option>
                    <option value="name">姓氏</option>
                </select>
                <input id="search_field" type="text" name="search" style="padding: 5px;margin-left: 60px;border-top-left-radius: 0;border-bottom-left-radius: 0;border-left: none;" placeholder="...">
                <input style="float: right;" type="submit" value="查詢">
            </form>
        {% endif %}
        {% if last_invoices %}
            <div style="clear: both">
                <p style="margin-top: 10px; font-size: 30px;">最新訂單:</p>
                <ul class="invoice_list">
                {% for invoice in last_invoices %}
                  <a href="{% url 'invoice:search' %}{{ invoice.invoice_id }}">
                    <li id="invoice_detail_container">
                        <div id="first_name_container"><span id="first_name">{{ invoice.first_name }}</span><span class="invoice_id">#{{ invoice.invoice_id }}</span></div>
                        <div id="invoice_detail_inner_container">
                            <p>地址: {{ invoice.address }}</p>
                            <p>電話: {{ invoice.contact_number }}</p>
                        </div>
                    </li>
                  </a>
                {% endfor %}
                </ul>
            </div>
        {% endif %}
      {% if invoices %}
          <div style="clear: both">
              <p style="margin-top: 10px; font-size: 30px;">搜索结果:</p>
              <ul class="invoice_list">
                  {% for invoice in invoices %}
                  <a href="{% url 'invoice:search' %}{{ invoice.invoice_id }}">
                    <li id="invoice_detail_container">
                        <div id="first_name_container"><span id="first_name">{{ invoice.first_name }}</span><span class="invoice_id">#{{ invoice.invoice_id }}</span></div>
                        <div id="invoice_detail_inner_container">
                            <p>地址: {{ invoice.address }}</p>
                            <p>電話: {{ invoice.contact_number }}</p>
                        </div>
                    </li>
                  </a>
                  {% endfor %}
              </ul>
              <div>
                <ul id='page_number_list'>
                  {% for page in pages %}
                  <li>
                    {% if page == current_page %}
                      <span>{{ page|add:"1" }}</span>
                    {% else %}
                      <a href="{% url 'invoice:search' %}?search={{ str }}&cat={{ cat }}&p={{ page|add:"1" }}">{{ page|add:"1" }}</a>
                    {% endif %}
                  </li>
                  {% endfor %}
                </ul>
              </div>
          </div>
      {% endif %}
      {% if invoice %}
        <div id="invoice">
            {% if invoice.status == 'D' %}
                <div id="invoice_status_bar" class="deleted">
                    <p>已刪除</p>
                </div>
            {% elif invoice.status == 'U' %}
                <div id="invoice_status_bar" class="uncompleted">
                    <p>未完成</p>
                </div>
            {% elif invoice.status == 'C' %}
                <div id="invoice_status_bar" class="completed">
                    <p>已完成</p>
                </div>
            {% elif invoice.status == 'W' %}
                <div id="invoice_status_bar" class="waiting">
                    <p>等待確認</p>
                </div>
            {% endif %}

            <nav id="invoice_detail_container" class="detail">
                <div id="first_name_container">
                    <span id="first_name">{{ invoice.first_name }}</span>
                    <span class="invoice_id"><label id="star"></label>#<label id="invoice_id">{{ invoice.invoice_id }}</label></span>
                </div>
                <div id="invoice_detail_inner_container">
                    <p>地址: <span id="address">{{ invoice.address }}</span></p>
                    <p>電話1: <a style="color: blue" href="tel:{{ invoice.contact_number }}">{{ invoice.contact_number }}</a></p>
                    <p>電話2: <a style="color: blue" href="tel:{{ invoice.home_number}}">{{ invoice.home_number }}</a></p>
                    {% if invoice.payment_type == 'V' %}
                    <p>付款方式: Visa</p>
                    {% elif invoice.payment_type == 'C' %}
                    <p>付款方式: 現金</p>
                    {% elif invoice.payment_type == 'E' %}
                    <p>付款方式: EPS</p>
                    {% endif %}
                    <p>開單時間: {{ invoice.first_created }}</p>
                    <p>最後更改: {{ invoice.last_update }}</p>
                </div>
                {% if invoice.status != 'D' %}
                    <div id="invoice_button_container">
                        <a href="/invoice/edit/{{ invoice.invoice_id }}" id="edit_button"></a>
                        <a href="javascript:;" id="draw_button"></a>
                        <a href="{% url 'invoice:print' %}?invoice={{ invoice.invoice_id }}" id="print_button"></a>
                        <a href="{% url 'invoice:delete' %}?invoice={{ invoice.invoice_id }}" class="right_button" id="delete_button"></a>
                        {% if invoice.status == 'U' %}
                            <a href="{% url 'invoice:confirm' %}?invoice={{ invoice.invoice_id }}" class="right_button" id="complete_button"></a>
                        {% elif invoice.status == 'C' %}

                        {% endif %}
                    </div>
                {% endif %}
            </nav>
            {% if invoice.is_custom_made == True %}
                <p class="is_custom_made_indicator" id="custom_made">訂造</p>
            {% elif invoice.is_custom_made == False %}
                <p class="is_custom_made_indicator">現成</p>
            {% endif %}
            <div id="product_cell_container">
                <table>
                    <tr>
                        <th>编號</th>
                        <th>描述</th>
                        <th>顔色</th>
                        <th>追加</th>
                        <th>價錢</th>
                    </tr>
                    {% if products %}
                        {% for product in products %}
                        <tr class="product_cell">
                            <td id="name_tag">{{ product.product.serial_number }}</td>
                            <td>{{ product.product.description }}</td>
                            <td id="color_tag">{{ product.get_color_display }}</td>
                            <td id="side_note_tag">{{ product.side_note }}</td>
                            <td id="quantity_tag">${{ product.product.price }} X {{ product.quantity }}</td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                    {% if custom_products %}
                        {% for product in custom_products %}
                        <tr class="product_cell">
                            <td id="name_tag">{{ product.name }}</td>
                            <td>/</td>
                            <td id="color_tag">{{ product.color }}</td>
                            <td id="side_note_tag">{{ product.side_note }}</td>
                            <td id="quantity_tag">${{ product.price }} X {{ product.quantity }}</td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                    <tr>
                        <td colspan="4" style="text-align: right;border:none;">總值: </td>
                        <td>${{ invoice.total_amount }}</td>
                    </tr>
                    <tr>
                        <td colspan="4" style="text-align: right;border:none;">回贈: </td>
                        <td>${{ invoice.discount }}</td>
                    </tr>
                    <tr>
                        <td colspan="4" style="text-align: right;border:none;">訂金: </td>
                        <td>${{ invoice.deposit }}</td>
                    </tr>
                    <tr>
                        <td colspan="4" style="text-align: right;border:none;">尚欠: </td>
                        <td>${{ invoice.remaining }}</td>
                    </tr>
                    <tr>
                        <td colspan="4" style="text-align: right;border:none;">經銷人: </td>
                        <td>{{ invoice.sales.sales_name }}</td>
                    </tr>
                </table>
            </div>
            <div id="price_container">
                <p id="search_additional_note_box">{{ invoice.additional_note }}</p>
            </div>
        </div>
        <div class="backdrop" id="backdrop">
          <div id="simple-draw">
            <div id="draw-button-container">
                <div id="draw_button_middle">
                    <a href="javascript:void(0)" id="draw_clear_button">Clear</a>
                </div>
                <a href="javascript:void(0)" id="draw_close_button"></a>
            </div>
          </div>
        </div>
      {% endif %}
      {% if error %}
          <p style="padding: 10px; font-size: 30px;margin: 20px 0;">找不到訂單...</p>
      {% endif %}
    </div>
  </body>
</html>