Apple/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth.views import login
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from mainsite.views import set_language

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^lan/(?P<language>en|jp|zh-hant)$', set_language),
    url(r'^invoice/', include('invoice.urls')),
    url(r'^accounts/login/$', login)
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mainsite.urls')),
)

invoice/urls.py
from django.conf.urls import url

from . import views

app_name = 'invoice'
urlpatterns = [
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^$', views.root, name='root'),
    url(r'^search/$', views.search, name='search'),
    url(r'^search/(?P<invoice_id>\d+)$', views.search_detail, name='search_detail'),
    url(r'^choose/$', views.choose_create_invoice, name='choose_create_invoice'),
    url(r'^create/$', views.create, name='create'),
    url(r'^status/delete/$', views.delete, name='delete'),
    url(r'^status/confirm/$', views.confirm, name='confirm'),
    url(r'^edit/(?P<invoice_id>\d+)$', views.edit, name='edit'),
    url(r'^drawing/$', views.drawing, name='drawing'),
    url(r'^print/$', views.print_invoice, name='print'),
    url(r'^print_check/$', views.print_check_invoice, name='print_check'),
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^stats/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})$', views.stats, name='stats'),
    url(r'^check/$', views.check, name='check'),
    # url used for returning json objects (ajax)
    url(r'^furniture/$', views.get_furniture, name='get_furniture'),
    url(r'^edit/(?P<invoice_id>\d+)/invoice_products$', views.get_invoice_products, name='get_invoice_products'),
    url(r'^edit/(?P<invoice_id>\d+)/invoice_custom_products$', views.get_invoice_custom_products, name='get_invoice_custom_products')
]

mainsite/urls.py
from django.conf.urls import url

from . import views

app_name = 'mainsite'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'landing/$', views.landing, name='landing'),
    url(r'^apple/$', views.apple, name='apple'),
    url(r'^tinyuen/$', views.tinyuen, name='tinyuen'),
    url(r'^bedroom/$', views.bedroom, name='bedroom'),
    url(r'^livingroom/$', views.livingroom, name='livingroom'),
    url(r'^studyroom/$', views.studyroom, name='studyroom'),
    url(r'^category/$', views.category_main, name='category_main'),
    url(r'^category/(?P<category>[0-9]+)/$', views.category, name='category'),
    url(r'^product/(?P<product>[0-9]+)/$', views.product, name='product'),
    url(r'^members/$', views.members_page, name='members_page'),
]

invoice/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from base64 import b64decode
from datetime import datetime
import re

from invoice.models import Product, InvoiceProduct, Invoice, InvoiceCustomProduct, Sales

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, QueryDict
from django.urls import reverse

from django.http import JsonResponse
from django.core.files.base import ContentFile

from django.conf import settings
import subprocess

from printer import PDFCreator

from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

from django.views import generic
from django.utils.html import escape

from django.contrib.auth.decorators import login_required, user_passes_test

from django.core.exceptions import ObjectDoesNotExist

from django.forms.models import model_to_dict

import json
import urllib


# TO-DO: - Check Chinese character database compatibility
#        - implementing 訂造單
#        - implementing discount  (DONE)
#        - implementing editable invoice  (DONE)
#        - implementing furniture colours and (maybe) furniture photos (DONE)


# return a queryset object with latest invoices accorded by invoice_id in acending order
def get_uncompleted_invoices(number_of_invoices):
    latest_invoices = Invoice.objects.filter(status='U').order_by('last_update')[:number_of_invoices]
    return latest_invoices


# return True if product was deleted, False if products were not deleted
def delete_invoice_product(invoice_id):
    if InvoiceProduct.objects.filter(invoice_id=invoice_id).count() != 0:
        try:
            InvoiceProduct.objects.filter(invoice_id=invoice_id).delete()
        except IndexError:
            return False
        else:
            return True
    else:
        return False


def delete_invoice_custom_product(invoice_id):
    print(invoice_id)
    invoice_custom_products = InvoiceCustomProduct.objects.filter(invoice_id=invoice_id)
    try:
        invoice_custom_products.delete()
    except IndexError:
        return False
    else:
        return True

def change_status(invoice_id, status):
    try:
        Invoice.objects.filter(pk=invoice_id).update(status=status)
    except IndexError:
        return False
    return True


from django.contrib.auth import logout

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/invoice')

def user_group_check(user):
    return user.groups.filter(name="Sales").exists()

@user_passes_test(user_group_check, login_url='/accounts/login/')
def root(request):
    return render(request, 'invoice/index.html', {'user': request.user})

@user_passes_test(user_group_check, login_url='/accounts/login/')
def delete(request):
    if request.method == "GET":
        invoice_id = request.GET.get("invoice")
        if invoice_validation(invoice_id):
            if change_status(invoice_id, Invoice.Deleted):
                return HttpResponseRedirect('/invoice/search/?search=' + invoice_id)
            else:
                return HttpResponse("Please enter a valid invoice id")
        else:
            return HttpResponse("Please enter a valid invoice id")
    else:
        return HttpResponse("error")

@user_passes_test(user_group_check, login_url='/accounts/login/')
def confirm(request):
    if request.method == "GET":
        invoice_id = request.GET.get("invoice")
        if invoice_validation(invoice_id):
            if change_status(invoice_id, Invoice.Completed):
                return HttpResponseRedirect('/invoice/search/?search=' + invoice_id)
            else:
                return HttpResponse("Please enter a valid invoice id")
        else:
            return HttpResponse("Please enter a valid invoice id")
    else:
        return HttpResponse("error")

@user_passes_test(user_group_check, login_url='/accounts/login/')
def drawing(request):
    if request.method == "GET":
        invoice_id = request.GET.get("invoice")
        try:
            invoice = Invoice.objects.filter(pk=invoice_id).values()[0]
        except IndexError:
            return False
        return JsonResponse({'image': invoice['drawing']})
    elif request.method == "POST":
        invoice_id = request.POST.get("invoice")
        try:
            invoice = Invoice.objects.filter(pk=invoice_id)
        except IndexError:
            return False
        else:
            _, image_data = request.POST['image'].split(',')
            image_data = b64decode(image_data)
            image_name = invoice_id + ".png"
            invoice.update(drawing=ContentFile(image_data, image_name))
            return JsonResponse({'success': True})

@user_passes_test(user_group_check, login_url='/accounts/login/')
def choose_create_invoice(request):
    return render(request, 'invoice/choose_create_invoice.html', {})

@user_passes_test(user_group_check, login_url='/accounts/login/')
def search_detail(request, invoice_id=-1):
    if request.method == "GET":
        if invoice_id is not -1:
            if invoice_validation(invoice_id):
                try:
                    invoice = Invoice.objects.get(pk=invoice_id)
                except IndexError:
                    return render(request, 'invoice/search.html', {'error': True})
                else:
                    invoice_products = InvoiceProduct.objects.filter(invoice_id=invoice_id)
                    custom_products = InvoiceCustomProduct.objects.filter(invoice_id=invoice_id)
                    return render(request, 'invoice/search.html', {'invoice': invoice, 'products': invoice_products, 'custom_products': custom_products})
            else:
                return render(request, 'invoice/search.html', {'error': True})

@user_passes_test(user_group_check, login_url='/accounts/login/')
def search(request):
    if request.method == "GET":
        string = request.GET.get("search", '')
        category = request.GET.get("cat", '')
        invoice = request.GET.get("invoice", '')
        # category: address, name, number

        # if a invoice_id is provided show it's detail and products
        # else show the latest invoices created
        if string is not '':
            if category == "address":
                invoices = Invoice.objects.filter(address__contains=string)
            elif category == "name":
                invoices = Invoice.objects.filter(first_name__contains=string)
            elif category == "number":
                invoices = Invoice.objects.filter(contact_number__contains=string)
            elif category == "invoice_id":
                invoices = Invoice.objects.filter(invoice_id__contains=string)

            if invoices.exists():
                noi = 8
                nop = (invoices.count() / (noi + 1)) + 1
                page = int(request.GET.get("p", 1))

                first_item = noi*(page-1)
                last_item = noi*page
                if page == nop:
                    last_item = invoices.count()

                return render(request, 'invoice/search.html', {'invoices': invoices[first_item:last_item], 'current_page': page-1, 'pages': range(nop), 'cat': category, 'str': string})
            else:
                return render(request, 'invoice/search.html', {'error': True})

        else:
            return render(request, 'invoice/search.html', {
                'last_invoices': Invoice.objects.all().order_by("-last_update")[:10]})

@user_passes_test(user_group_check, login_url='/accounts/login/')
def edit(request, invoice_id=-1):
    if request.method == "GET":
        # if a invoice_id is provided show it's detail and products
        # else show the latest invoices created
        if invoice_id is not -1:
            if invoice_validation(invoice_id):
                try:
                    invoice = Invoice.objects.get(pk=invoice_id)
                except IndexError:
                    return render(request, 'invoice/edit.html', {'error': True})
                else:
                    if not invoice.is_custom_made:
                        invoice_products = InvoiceProduct.objects.filter(invoice_id=invoice_id)
                        custom_products = InvoiceCustomProduct.objects.filter(invoice_id=invoice_id)
                        return render(request, 'invoice/edit.html',
                                      {'invoice': invoice, 'products': invoice_products, 'custom_products': custom_products})
                    else:
                        custom_products = InvoiceCustomProduct.objects.filter(invoice_id=invoice_id).values()
                        return render(request, 'invoice/edit_custom.html', {'invoice': invoice, 'products': custom_products})
            else:
                return render(request, 'invoice/edit.html', {'error': True})
        else:
            return render(request, 'invoice/edit.html', {'error': True})
    # if method is 'POST' or 'HEAD'
    else:
        # create a mutable copy of the POST item
        r = request.POST.copy()
        r.pop('csrfmiddlewaretoken', None)
        name = r.pop('firstName', None)[0]
        tel = r.pop('contactNum', None)[0]
        homeNum = r.pop('homeNum', None)[0]
        address = r.pop('address', None)[0]
        payment_type = r.pop('payment_type', None)[0]
        additional_note = r.pop('additional_note', None)[0]
        deposit = int(r.pop('deposit', None)[0])
        price = int(r.pop('price', None)[0])
        discount = int(r.pop('discount', None)[0])

        # check if the invoice_id is valid
        if invoice_validation(invoice_id):
            try:
                invoice = Invoice.objects.get(pk=invoice_id)
            except IndexError:
                return render(request, 'invoice/failure.html', {})
            else:
                delete_invoice_custom_product(invoice_id)
                delete_invoice_product(invoice_id)
                # value stores the json of the product
                for key, value in r.items():
                    # parse json string

invoice/templates/apple/custom.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="傢俬, 紅蘋果傢俬專賣店, 蘋果傢俬店, 傢俬紅蘋果傢俬香港, 紅蘋果, 蘋果傢俬,  紅蘋果傢俬專門店, 紅蘋果傢俱, 紅蘋果傢具, 紅蘋果香港, 紅蘋果傢私, 金美夢床褥, sweet dream mattress, 訂造傢俬, 紅蘋果傢俬訂造, 芝華仕梳化, cheers sofa, ulfenbo, 歐化寶,sweet dream金美夢,royce mattress, 箂斯護,luxury dream, 睡康寧,斯林白蘭,slumberland, 實惠都有紅蘋果傢俬, E1環保板,紅蘋果傢俬床, 紅蘋果傢俱專門店, red apple furniture in hong kong本公司銷售紅蘋果傢俬,家居設計,訂造傢俱傢俬,兒童傢俬傢具,另有芝華仕梳化,金美夢床褥,餐椅">
  <meta name="keywords" content="傢俬, 紅蘋果香港, 紅蘋果, 蘋果, 紅蘋果傢俬專賣店, 蘋果傢俬店, red apple 傢俬 紅蘋果傢俬香港, red apple furniture hong kong , red apple furniture hk, red apple furniture in hong kong 本公司銷售紅蘋果傢俬,家居設計,訂造傢俱傢俬,兒童傢俬傢具,另有芝華仕梳化,金美夢床褥,餐&#26545;餐椅,可代客訂造梳化沙發沙化地柜,組合床,床褥,ulfenbo歐化寶,sweet dream金美夢,royce mattress箂斯護,luxury dream 睡康寧,斯林白蘭slumberland特約經銷商">
  {% load i18n %}
  <title>{{ category_name }} | {% trans "蘋果傢俬"%}</title>
  <!-- Bootstrap -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'common/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'apple/css/common.css' %}">
  <link rel="stylesheet" href="{% static 'common/owlcarousel/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'common/owlcarousel/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'common/colorbox/colorbox.css' %}">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
</head>
<body>
<!-- HEADER -->
<header id="top">
  <div class="head-content">
    <div class="center title-container">
      <h1>{{ category_name }}</h1>
    </div>
  </div>
</header>
<!-- / HEADER -->

<nav>
  <div class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
      	<div class="navbar-header">
           <div class="breadcrums">
             <a href="/">{% trans "主頁"%}</a>
             <span> / {{ category_name }}</span>
           </div>
      	</div>
       </div>
    </div>
</nav>

<section id="main-body">
  <div class="container-full container">
    <div class="row">
      <div class="col-xs-12 text-center">
        <div style="padding: 5px;margin: 10px 0;">
          <h2>「格」新</h2>
          <h4>{% blocktrans %}蘋果傢俬為客人度身訂造傢俬，務求為您帶來一個舒適的家。如有需要，可向職員查詢{% endblocktrans %}</h4>
          <h4><a href="" style="text-decoration:underline;color: black;padding: 5px;border-radius: 5px;background: white;text-shadow: none;">{% trans "聯絡我們"%}</a></h4>
        </div>
      </div>
    </div>
  </div>
  <div class="album-container">
    {% for path in paths%}
    <div class="photo-container">
      <a class="gallery" href="{{ path }}">
        <img src="{{ path }}" style="width: 100%;"/>
      </a>
    </div>
    {% endfor %}
  </div>
</section>

<!--  SECTION-1 -->


<footer class="text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <p>{% blocktrans %}Copyright © MyWebsite. All rights reserved.{% endblocktrans %}</p>
      </div>
    </div>
  </div>
</footer>
<!-- / FOOTER -->
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script type="text/javascript" src="{% static 'common/jquery-3.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'common/parallax/parallax.js' %}"></script>
<script type="text/javascript" src="{% static 'common/colorbox/jquery.colorbox-min.js' %}"></script>
<script type="text/javascript" src="{% static 'apple/js/album.js' %}"></script>
<script>
  $(function() {
    $('a.gallery').colorbox({rel:'gallery', maxWidth: "100%", maxHeight: "100%"});
    setTimeout(resize, 1000);
  });
  $(window).resize(resize);
</script>
<script type="text/javascript" src="{% static 'common/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'common/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

invoice/templates/apple/members.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>蘋果傢俬</title>
  <!-- Bootstrap -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'common/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'apple/css/common.css' %}">
  <link rel="stylesheet" href="{% static 'apple/css/members.css' %}">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
  <script>
    var currentColor = null;
    function changeBackground(color){
      $("#color").removeClass(currentColor);
      $("#color").addClass(color);
      $("a."+color).addClass("no-background");
      $("a."+currentColor).removeClass("no-background");
      currentColor = color;
    }
  </script>
</head>

<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand navbar-center scroll_page" id="nav-brand" href="/"><span class="navbar-logo logo" /></a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->

    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<section class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <h2>你的訂單</h2>
    </div>
  </div>
  <div class="row">
    {% for invoice in invoices %}
    <div class="col-xs-6 col-sm-6 col-md-4 invoice-card-container">
      <div class="invoice-card">

      </div>
    </div>
    {% endfor %}
  </div>
</section>

<footer class="text-center">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <p>Copyright © MyWebsite. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>
<script type="text/javascript" src="{% static 'common/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'common/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

invoice/templates/apple/product_category.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="傢俬, 紅蘋果傢俬專賣店, 蘋果傢俬店, 傢俬紅蘋果傢俬香港, 紅蘋果, 蘋果傢俬,  紅蘋果傢俬專門店, 紅蘋果傢俱, 紅蘋果傢具, 紅蘋果香港, 紅蘋果傢私, 金美夢床褥, sweet dream mattress, 訂造傢俬, 紅蘋果傢俬訂造, 芝華仕梳化, cheers sofa, ulfenbo, 歐化寶,sweet dream金美夢,royce mattress, 箂斯護,luxury dream, 睡康寧,斯林白蘭,slumberland, 實惠都有紅蘋果傢俬, E1環保板,紅蘋果傢俬床, 紅蘋果傢俱專門店, red apple furniture in hong kong本公司銷售紅蘋果傢俬,家居設計,訂造傢俱傢俬,兒童傢俬傢具,另有芝華仕梳化,金美夢床褥,餐椅">
  <meta name="keywords" content="傢俬, 紅蘋果香港, 紅蘋果, 蘋果, 紅蘋果傢俬專賣店, 蘋果傢俬店, red apple 傢俬 紅蘋果傢俬香港, red apple furniture hong kong , red apple furniture hk, red apple furniture in hong kong 本公司銷售紅蘋果傢俬,家居設計,訂造傢俱傢俬,兒童傢俬傢具,另有芝華仕梳化,金美夢床褥,餐&#26545;餐椅,可代客訂造梳化沙發沙化地柜,組合床,床褥,ulfenbo歐化寶,sweet dream金美夢,royce mattress箂斯護,luxury dream 睡康寧,斯林白蘭slumberland特約經銷商">
  {% load i18n %}
  <title>{{ category.name }} | {% trans "蘋果傢俬"%}</title>
  <!-- Bootstrap -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'common/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'apple/css/common.css' %}">
  <link rel="stylesheet" href="{% static 'apple/css/product_category.css' %}">
  <link rel="stylesheet" href="{% static 'common/colorbox/colorbox.css' %}">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
  <script>
  $(document).ready(function () {
    $('[data-toggle="offcanvas"]').click(function () {
      $('#sidebar').toggleClass('active');
    });
  });
  </script>
</head>
<body>
<!-- HEADER -->
<header id="top">
  <div class="head-content">
    <div class="center title-container">
      <h1>{{ category.name }}</h1>
    </div>
  </div>
</header>
<!-- / HEADER -->

<nav>
  <div class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
      	<div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".sidebar-nav">
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <div class="breadcrums">
             <a href="/">{% trans "主頁"%}</a>
             <span>/ {{ category.name }}</span>
           </div>
      	</div>
       </div>
    </div>
</nav>


<div id="main-body" class="container-full container">
  <div class="row">
    <div id="sidebar" class="col-xs-7 col-sm-4"  style="border:1px solid lightgray;border-top: none;border-left: none;border-bottom: none;">
        <ul class="nav nav-pills nav-stacked">
          {% for parent_cat in parent_categories %}
            {% if parent_category == parent_cat %}
            <li class="active"><a href="/category/{{ parent_cat.id }}/">{{ parent_cat.name }}</a></li>
              {% for sub_cat in sub_categories %}
              {% if category == sub_cat %}
              <li class="sub_cat active"><a href="/category/{{ sub_cat.id }}/">{{ sub_cat.name }}</a></li>
              {% else %}
              <li class="sub_cat"><a href="/category/{{ sub_cat.id }}/">{{ sub_cat.name }}</a></li>
              {% endif %}
              {% endfor %}
            {% else %}
            <li><a href="/category/{{ parent_cat.id }}/">{{ parent_cat.name }}</a></li>
            {% endif %}
          {% endfor %}
        </ul>
    </div>
    <div id="main" class="col-sm-8">
      <div class="row" style="padding: 10px;">
        {% if products %}
        {% for product in products %}
        <div class="col-xs-6 col-sm-4 grid">
          <div class="card-container">
            <a href="/product/{{ product.product_id }}/">
              <div class="img-backdrop"></div>
              <img src="/media/{{ product.thumbnail }}"/>
              <div class="caption">
                <div class="serial_number">
                  <p>{{ product.serial_number }}</p>
                </div>
                <div class="caption-container">
                  <p class="description">{{ product.description }}</p>
                </div>
              </div>
            </a>
          </div>
        </div>
        {% endfor %}
        {% elif sub_categories %}
        {% for sub_category in sub_categories %}
        <div class="col-xs-6 col-sm-4 grid">
          <div class="card-container">
            <a href="/category/{{ sub_category.id }}">
              <div class="caption">
                <div class="serial_number">
                  <p>{{ sub_category.name }}</p>
                </div>
              </div>
            </a>
          </div>
        </div>
        {% endfor %}
        {% endif %}
        <div class="col-xs-12" style="padding: 10px;">
          <ul id='page_number_list'>
            {% for page in pages %}
              {% if page == current_page %}
              <li class="active"><span>{{ page|add:"1" }}</span></li>
              {% else %}
              <li><a href="{% url 'mainsite:category' category.id %}?p={{ page|add:"1" }}">{{ page|add:"1" }}</a></li>
              {% endif %}
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- / FOOTER -->
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script type="text/javascript" src="{% static 'common/jquery-3.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'common/parallax/parallax.js' %}"></script>
<script type="text/javascript" src="{% static 'common/colorbox/jquery.colorbox-min.js' %}"></script>
<script src="{% static 'common/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>