Apple/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.auth.views import login
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from mainsite.views import set_language

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^lan/(?P<language>en|jp|zh-hant)$', set_language),
    url(r'^invoice/', include('invoice.urls')),
    url(r'^accounts/login/$', login)
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mainsite.urls')),
)

invoice/urls.py
from django.conf.urls import url

from . import views

app_name = 'invoice'
urlpatterns = [
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^$', views.root, name='root'),
    url(r'^search/$', views.search, name='search'),
    url(r'^search/(?P<invoice_id>\d+)$', views.search_detail, name='search_detail'),
    url(r'^choose/$', views.choose_create_invoice, name='choose_create_invoice'),
    url(r'^create/$', views.create, name='create'),
    url(r'^status/delete/$', views.delete, name='delete'),
    url(r'^status/confirm/$', views.confirm, name='confirm'),
    url(r'^edit/(?P<invoice_id>\d+)$', views.edit, name='edit'),
    url(r'^drawing/$', views.drawing, name='drawing'),
    url(r'^print/$', views.print_invoice, name='print'),
    url(r'^print_check/$', views.print_check_invoice, name='print_check'),
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^stats/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})$', views.stats, name='stats'),
    url(r'^check/$', views.check, name='check'),
    # url used for returning json objects (ajax)
    url(r'^furniture/$', views.get_furniture, name='get_furniture'),
    url(r'^edit/(?P<invoice_id>\d+)/invoice_products$', views.get_invoice_products, name='get_invoice_products'),
    url(r'^edit/(?P<invoice_id>\d+)/invoice_custom_products$', views.get_invoice_custom_products, name='get_invoice_custom_products')
]

invoice/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from base64 import b64decode
from datetime import datetime
import re

from invoice.models import Product, InvoiceProduct, Invoice, InvoiceCustomProduct, Sales

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, QueryDict
from django.urls import reverse

from django.http import JsonResponse
from django.core.files.base import ContentFile

from django.conf import settings
import subprocess

from printer import PDFCreator

from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

from django.views import generic
from django.utils.html import escape

from django.contrib.auth.decorators import login_required, user_passes_test

from django.core.exceptions import ObjectDoesNotExist

from django.forms.models import model_to_dict

import json
import urllib


# TO-DO: - Check Chinese character database compatibility
#        - implementing 訂造單
#        - implementing discount  (DONE)
#        - implementing editable invoice  (DONE)
#        - implementing furniture colours and (maybe) furniture photos (DONE)


# return a queryset object with latest invoices accorded by invoice_id in acending order
def get_uncompleted_invoices(number_of_invoices):
    latest_invoices = Invoice.objects.filter(status='U').order_by('last_update')[:number_of_invoices]
    return latest_invoices


# return True if product was deleted, False if products were not deleted
def delete_invoice_product(invoice_id):
    if InvoiceProduct.objects.filter(invoice_id=invoice_id).count() != 0:
        try:
            InvoiceProduct.objects.filter(invoice_id=invoice_id).delete()
        except IndexError:
            return False
        else:
            return True
    else:
        return False


def delete_invoice_custom_product(invoice_id):
    print(invoice_id)
    invoice_custom_products = InvoiceCustomProduct.objects.filter(invoice_id=invoice_id)
    try:
        invoice_custom_products.delete()
    except IndexError:
        return False
    else:
        return True

def change_status(invoice_id, status):
    try:
        Invoice.objects.filter(pk=invoice_id).update(status=status)
    except IndexError:
        return False
    return True


from django.contrib.auth import logout

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/invoice')

def user_group_check(user):
    return user.groups.filter(name="Sales").exists()

@user_passes_test(user_group_check, login_url='/accounts/login/')
def root(request):
    return render(request, 'invoice/index.html', {'user': request.user})

@user_passes_test(user_group_check, login_url='/accounts/login/')
def delete(request):
    if request.method == "GET":
        invoice_id = request.GET.get("invoice")
        if invoice_validation(invoice_id):
            if change_status(invoice_id, Invoice.Deleted):
                return HttpResponseRedirect('/invoice/search/?search=' + invoice_id)
            else:
                return HttpResponse("Please enter a valid invoice id")
        else:
            return HttpResponse("Please enter a valid invoice id")
    else:
        return HttpResponse("error")

@user_passes_test(user_group_check, login_url='/accounts/login/')
def confirm(request):
    if request.method == "GET":
        invoice_id = request.GET.get("invoice")
        if invoice_validation(invoice_id):
            if change_status(invoice_id, Invoice.Completed):
                return HttpResponseRedirect('/invoice/search/?search=' + invoice_id)
            else:
                return HttpResponse("Please enter a valid invoice id")
        else:
            return HttpResponse("Please enter a valid invoice id")
    else:
        return HttpResponse("error")

@user_passes_test(user_group_check, login_url='/accounts/login/')
def drawing(request):
    if request.method == "GET":
        invoice_id = request.GET.get("invoice")
        try:
            invoice = Invoice.objects.filter(pk=invoice_id).values()[0]
        except IndexError:
            return False
        return JsonResponse({'image': invoice['drawing']})
    elif request.method == "POST":
        invoice_id = request.POST.get("invoice")
        try:
            invoice = Invoice.objects.filter(pk=invoice_id)
        except IndexError:
            return False
        else:
            _, image_data = request.POST['image'].split(',')
            image_data = b64decode(image_data)
            image_name = invoice_id + ".png"
            invoice.update(drawing=ContentFile(image_data, image_name))
            return JsonResponse({'success': True})

@user_passes_test(user_group_check, login_url='/accounts/login/')
def choose_create_invoice(request):
    return render(request, 'invoice/choose_create_invoice.html', {})

@user_passes_test(user_group_check, login_url='/accounts/login/')
def search_detail(request, invoice_id=-1):
    if request.method == "GET":
        if invoice_id is not -1:
            if invoice_validation(invoice_id):
                try:
                    invoice = Invoice.objects.get(pk=invoice_id)
                except IndexError:
                    return render(request, 'invoice/search.html', {'error': True})
                else:
                    invoice_products = InvoiceProduct.objects.filter(invoice_id=invoice_id)
                    custom_products = InvoiceCustomProduct.objects.filter(invoice_id=invoice_id)
                    return render(request, 'invoice/search.html', {'invoice': invoice, 'products': invoice_products, 'custom_products': custom_products})
            else:
                return render(request, 'invoice/search.html', {'error': True})

@user_passes_test(user_group_check, login_url='/accounts/login/')
def search(request):
    if request.method == "GET":
        string = request.GET.get("search", '')
        category = request.GET.get("cat", '')
        invoice = request.GET.get("invoice", '')
        # category: address, name, number

        # if a invoice_id is provided show it's detail and products
        # else show the latest invoices created
        if string is not '':
            if category == "address":
                invoices = Invoice.objects.filter(address__contains=string)
            elif category == "name":
                invoices = Invoice.objects.filter(first_name__contains=string)
            elif category == "number":
                invoices = Invoice.objects.filter(contact_number__contains=string)
            elif category == "invoice_id":
                invoices = Invoice.objects.filter(invoice_id__contains=string)

            if invoices.exists():
                noi = 8
                nop = (invoices.count() / (noi + 1)) + 1
                page = int(request.GET.get("p", 1))

                first_item = noi*(page-1)
                last_item = noi*page
                if page == nop:
                    last_item = invoices.count()

                return render(request, 'invoice/search.html', {'invoices': invoices[first_item:last_item], 'current_page': page-1, 'pages': range(nop), 'cat': category, 'str': string})
            else:
                return render(request, 'invoice/search.html', {'error': True})

        else:
            return render(request, 'invoice/search.html', {
                'last_invoices': Invoice.objects.all().order_by("-last_update")[:10]})

@user_passes_test(user_group_check, login_url='/accounts/login/')
def edit(request, invoice_id=-1):
    if request.method == "GET":
        # if a invoice_id is provided show it's detail and products
        # else show the latest invoices created
        if invoice_id is not -1:
            if invoice_validation(invoice_id):
                try:
                    invoice = Invoice.objects.get(pk=invoice_id)
                except IndexError:
                    return render(request, 'invoice/edit.html', {'error': True})
                else:
                    if not invoice.is_custom_made:
                        invoice_products = InvoiceProduct.objects.filter(invoice_id=invoice_id)
                        custom_products = InvoiceCustomProduct.objects.filter(invoice_id=invoice_id)
                        return render(request, 'invoice/edit.html',
                                      {'invoice': invoice, 'products': invoice_products, 'custom_products': custom_products})
                    else:
                        custom_products = InvoiceCustomProduct.objects.filter(invoice_id=invoice_id).values()
                        return render(request, 'invoice/edit_custom.html', {'invoice': invoice, 'products': custom_products})
            else:
                return render(request, 'invoice/edit.html', {'error': True})
        else:
            return render(request, 'invoice/edit.html', {'error': True})
    # if method is 'POST' or 'HEAD'
    else:
        # create a mutable copy of the POST item
        r = request.POST.copy()
        r.pop('csrfmiddlewaretoken', None)
        name = r.pop('firstName', None)[0]
        tel = r.pop('contactNum', None)[0]
        homeNum = r.pop('homeNum', None)[0]
        address = r.pop('address', None)[0]
        payment_type = r.pop('payment_type', None)[0]
        additional_note = r.pop('additional_note', None)[0]
        deposit = int(r.pop('deposit', None)[0])
        price = int(r.pop('price', None)[0])
        discount = int(r.pop('discount', None)[0])

        # check if the invoice_id is valid
        if invoice_validation(invoice_id):
            try:
                invoice = Invoice.objects.get(pk=invoice_id)
            except IndexError:
                return render(request, 'invoice/failure.html', {})
            else:
                delete_invoice_custom_product(invoice_id)
                delete_invoice_product(invoice_id)
                # value stores the json of the product
                for key, value in r.items():
                    # parse json string

invoice/templates/invoice/stats/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Lumino - Dashboard</title>
{% load static %}
<link href="{% static 'common/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'invoice/stats/css/datepicker3.css' %}" rel="stylesheet">
<link href="{% static 'invoice/stats/css/styles.css' %}" rel="stylesheet">

<!--Icons-->
<script src="{% static 'invoice/stats/js/lumino.glyphs.js' %}"></script>

<!--[if lt IE 9]>
<script src="js/html5shiv.js"></script>
<script src="js/respond.min.js"></script>
<![endif]-->

</head>

<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="{% url 'invoice:root' %}"><span>Lumino</span>Admin</a>
				<ul class="user-menu">
					<li class="dropdown pull-right">
						<a href="#"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> {{ user.username }}</a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="#"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Profile</a></li>
							<li><a href="#"><svg class="glyph stroked gear"><use xlink:href="#stroked-gear"></use></svg> Settings</a></li>
							<li><a href="#"><svg class="glyph stroked cancel"><use xlink:href="#stroked-cancel"></use></svg> Logout</a></li>
						</ul>
					</li>
				</ul>
			</div>

		</div><!-- /.container-fluid -->
	</nav>
	<div class="col-lg-12 main">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">{% now "n" %}月份總結</h1>
			</div>
		</div><!--/.row-->
		<div class="row">
			<div class="col-xs-12 col-md-6 col-lg-6">
				<div class="panel panel-blue panel-widget ">
					<div class="row no-padding">
						<div class="col-sm-3 col-lg-5 widget-left">
							<svg class="glyph stroked bag"><use xlink:href="#stroked-bag"></use></svg>
						</div>
						<div class="col-sm-9 col-lg-7 widget-right">
							<div id="invoice_total_amount" class="large">${{ data.invoice_total_amount }}</div>
							<div class="text-muted">總額</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-md-6 col-lg-6">
				<div class="panel panel-orange panel-widget">
					<div class="row no-padding">
						<div class="col-sm-3 col-lg-5 widget-left">
							<svg class="glyph stroked empty-message"><use xlink:href="#stroked-folder"></use></svg>
						</div>
						<div class="col-sm-9 col-lg-7 widget-right">
							<div id="invoice_count" class="large">{{ data.invoice_count }}</div>
							<div class="text-muted">訂單數量</div>
						</div>
					</div>
				</div>
			</div>
		</div><!--/.row-->
		<div class="row">
			<div class="col-lg-12">
				<div  class="panel-red">
					<div class="panel-heading">銷量</div>
					<div class="panel-body">
						<div class="canvas-wrapper">
							<div id="calendar"></div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="canvas-wrapper">
						<canvas class="main-chart" id="line-chart" height="200" width="600"></canvas>
					</div>
				</div>
			</div>
		</div><!--/.row-->

		<div class="row">
			<div class="col-xs-6 col-md-3">
				<div class="panel panel-default">
					<div class="panel-body easypiechart-panel">
						<h4>New Orders</h4>
						<div class="easypiechart" id="easypiechart-blue" data-percent="92" ><span class="percent">92%</span>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-6 col-md-3">
				<div class="panel panel-default">
					<div class="panel-body easypiechart-panel">
						<h4>Comments</h4>
						<div class="easypiechart" id="easypiechart-orange" data-percent="65" ><span class="percent">65%</span>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-6 col-md-3">
				<div class="panel panel-default">
					<div class="panel-body easypiechart-panel">
						<h4>New Users</h4>
						<div class="easypiechart" id="easypiechart-teal" data-percent="56" ><span class="percent">56%</span>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-6 col-md-3">
				<div class="panel panel-default">
					<div class="panel-body easypiechart-panel">
						<h4>Visitors</h4>
						<div class="easypiechart" id="easypiechart-red" data-percent="27" ><span class="percent">27%</span>
						</div>
					</div>
				</div>
			</div>
		</div><!--/.row-->
	</div>	<!--/.main-->

	<script src="{% static 'common/jquery-3.1.1.min.js' %}"></script>
	<script src="{% static 'common/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'invoice/stats/js/chart.min.js' %}"></script>
	<script src="{% static 'invoice/stats/js/chart-data.js' %}"></script>
	<script src="{% static 'invoice/stats/js/easypiechart.js' %}"></script>
	<script src="{% static 'invoice/stats/js/easypiechart-data.js' %}"></script>
	<script src="{% static 'invoice/stats/js/bootstrap-datepicker.js' %}"></script>
	<script>
		$(function() {
			var lineChartData = {
				labels : ["12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00","21:00","22:00","23:00","24:00"],
				datasets : [
					{
						label: "My First dataset",
						fillColor : "rgba(48, 164, 255, 0.2)",
						strokeColor : "rgba(48, 164, 255, 1)",
						pointColor : "rgba(48, 164, 255, 1)",
						pointStrokeColor : "#fff",
						pointHighlightFill : "#fff",
						pointHighlightStroke : "rgba(48, 164, 255, 1)"
					}
				]
			};
			var chart1 = document.getElementById("line-chart").getContext("2d");
			$('#calendar').datepicker({maxViewMode: 0}).on('changeDate', function(e) {
				if (e.date !== undefined) {
					var month = (e.date.getMonth() + 1) > 9 ? ""+(e.date.getMonth() + 1) : "0"+(e.date.getMonth() + 1);
					var day = e.date.getDate() > 9 ? ""+e.date.getDate() : "0"+e.date.getDate();
					$.ajax({
						"url": window.location.href + e.date.getFullYear() + '/' + month + '/' + day,
						"method": "GET",
						"error": function (a, b, errorString) {
							console.log("Error: " + errorString)
						}
					}).done(function(data) {
						var invoices = data.data.invoices;
						var total = 0;
						var data = [];
						for (var i = 0;i < 13;i++) {
							data.push(0);
						}
						for (var i = 0;i < invoices.length;i++) {
							total += (invoices[i].total_amount - invoices[i].discount);
							var date = new Date(invoices[i].first_created);
							data[(date.getHours() - 12)] += (invoices[i].total_amount - invoices[i].discount);
						}
						lineChartData.datasets[0].data = data;
						window.myLine = new Chart(chart1).Line(lineChartData, {
							responsive: true
						});
						$("#invoice_total_amount").html("$"+total)
						$("#invoice_count").html(invoices.length)
					});
				}
	    });
		});
	</script>
</body>

</html>